package com.example.currencyconverter.domain.entity
import com.example.currencyconverter.R
enum class Currency(
    val fullName: String,
    val symbol: String,
    val flag: Int,
) {
    USD("US dollar", "$", R.drawable.ic_usa_flag),
    GBP("British pound", "£", R.drawable.ic_gbp_flag),
    EUR("Euro", "€", R.drawable.ic_eur_flag),
    AUD("Australian dollar", "$", R.drawable.ic_aud_flag),
    BGN("Bulgarian lev", "лв", R.drawable.ic_bgn_flag),
    BRL("Brazilian real", "R$",R.drawable.ic_brl_flag),
    CAD("Canadian dollar", "CA$",R.drawable.ic_cad_flag),
    CHF("Swiss franc", "CHF",R.drawable.ic_chf_flag),
    CNY("Chinese yuan", "¥",R.drawable.ic_cny_falg),
    CZK("Czech koruna", "Kč",R.drawable.ic_czk_flag),
    DKK("Danish krone", "kr",R.drawable.ic_dkk_flag),
    HKD("Hong Kong dollar", "HK$",R.drawable.ic_hkd_flag),
    HRK("Croatian kuna", "kn",R.drawable.ic_hrk_flag),
    HUF("Hungarian forint", "Ft",R.drawable.ic_huf_flag),
    IDR("Indonesian rupiah", "Rp",R.drawable.ic_idr_flag),
    ILS("Israeli new shekel", "₪",R.drawable.ic_ils_flag),
    INR("Indian rupee", "₹",R.drawable.ic_inr_flag),
    ISK("Icelandic króna", "kr",R.drawable.ic_isk_flag),
    JPY("Japanese yen", "¥",R.drawable.ic_jpy_flag),
    KRW("South Korean won", "₩",R.drawable.ic_krw_flag),
    MXN("Mexican peso", "MX$",R.drawable.ic_mxn_flag),
    MYR("Malaysian ringgit", "RM",R.drawable.ic_myr_flag),
    NOK("Norwegian krone", "kr",R.drawable.ic_nok_flag),
    NZD("New Zealand dollar", "NZ$",R.drawable.ic_nzd_flag),
    PHP("Philippine peso", "₱",R.drawable.ic_php_flag),
    PLN("Polish zloty", "zł",R.drawable.ic_pln_flag),
    RON("Romanian leu", "lei",R.drawable.ic_ron_flag),
    RUB("Russian ruble", "₽",R.drawable.ic_rub_flag),
    SEK("Swedish krona", "kr",R.drawable.ic_sek_flag),
    SGD("Singapore dollar", "S$",R.drawable.ic_sgd_flag),
    THB("Thai baht", "฿",R.drawable.ic_thb_flag),
    TRY("Turkish lira", "₺",R.drawable.ic_try_flag),
    ZAR("South African rand", "R",R.drawable.ic_zar_flag);
}