package com.example.currencyconverter.domain.entity
import com.example.currencyconverter.R
enum class Currency(
    val fullName: String,
    val symbol: String,
    val flag: Int,
) {
    USD("US Dollar", "$", R.drawable.ic_usa_flag),
    GBP("British Pound", "£", R.drawable.ic_gbp_flag),
    EUR("Euro", "€", R.drawable.ic_eur_flag),
    AUD("Australian Dollar", "$", R.drawable.ic_aud_flag),
    BGN("Bulgarian Lev", "лв", R.drawable.ic_bgn_flag),
    BRL("Brazilian Real", "R$",R.drawable.ic_brl_flag),
    CAD("Canadian Dollar", "CA$",R.drawable.ic_cad_flag),
    CHF("Swiss Franc", "CHF",R.drawable.ic_chf_flag),
    CNY("Chinese Yuan", "¥",R.drawable.ic_cny_falg),
    CZK("Czech Koruna", "Kč",R.drawable.ic_czk_flag),
    DKK("Danish Krone", "kr",R.drawable.ic_dkk_flag),
    HKD("Hong Kong Dollar", "HK$",R.drawable.ic_hkd_flag),
    HRK("Croatian Kuna", "kn",R.drawable.ic_hrk_flag),
    HUF("Hungarian Forint", "Ft",R.drawable.ic_huf_flag),
    IDR("Indonesian Rupiah", "Rp",R.drawable.ic_idr_flag),
    ILS("Israeli new Shekel", "₪",R.drawable.ic_ils_flag),
    INR("Indian Rupee", "₹",R.drawable.ic_inr_flag),
    ISK("Icelandic Króna", "kr",R.drawable.ic_isk_flag),
    JPY("Japanese Yen", "¥",R.drawable.ic_jpy_flag),
    KRW("South Korean Won", "₩",R.drawable.ic_krw_flag),
    MXN("Mexican Peso", "MX$",R.drawable.ic_mxn_flag),
    MYR("Malaysian Ringgit", "RM",R.drawable.ic_myr_flag),
    NOK("Norwegian Krone", "kr",R.drawable.ic_nok_flag),
    NZD("New Zealand Dollar", "NZ$",R.drawable.ic_nzd_flag),
    PHP("Philippine Peso", "₱",R.drawable.ic_php_flag),
    PLN("Polish Zloty", "zł",R.drawable.ic_pln_flag),
    RON("Romanian Leu", "lei",R.drawable.ic_ron_flag),
    RUB("Russian Ruble", "₽",R.drawable.ic_rub_flag),
    SEK("Swedish Krona", "kr",R.drawable.ic_sek_flag),
    SGD("Singapore Dollar", "S$",R.drawable.ic_sgd_flag),
    THB("Thai Baht", "฿",R.drawable.ic_thb_flag),
    TRY("Turkish Lira", "₺",R.drawable.ic_try_flag),
    ZAR("South African Rand", "R",R.drawable.ic_zar_flag);
}